[project]
name = "exercise3"
authors = [
  { name = "Oliver Ladores", email = "oliver.ladores@wvsu.edu.ph" }, 
  { name = "Khee Jay Galvez", email = "kheejay.galvez@wvsu.edu.ph" }, 
]
version = "0.1.0"
license = "BSD-3-Clause"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.1",
    "wikipedia>=1.4.0",
]
